# Generated by Django 3.2 on 2021-05-19 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='фото пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='название тега')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiarySiteApp.account')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='название заметки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание заметки')),
                ('planned_date', models.DateTimeField(blank=True, null=True, verbose_name='запланированная дата')),
                ('on_repeat', models.BooleanField(verbose_name='повторяется')),
                ('to_remind', models.BooleanField(verbose_name='напоминание')),
                ('remind_date', models.DateTimeField(blank=True, null=True, verbose_name='дата напоминания')),
                ('on_delete', models.BooleanField(default=False, verbose_name='удалено')),
                ('delete_date', models.DateField(blank=True, editable=False, null=True, verbose_name='дата удаления')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiarySiteApp.account')),
                ('tag', models.ManyToManyField(blank=True, to='DiarySiteApp.Tag')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'abstract': False,
            },
        ),
    ]
