# Generated by Django 3.2 on 2021-04-18 10:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='фото пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название категории')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiarySiteApp.account')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='название события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание события')),
                ('planned_date', models.DateTimeField(default=datetime.datetime(2021, 4, 19, 17, 43, 58, 845145), verbose_name='запланированная дата')),
                ('is_done', models.BooleanField(verbose_name='выполнено')),
                ('on_repeat', models.BooleanField(verbose_name='повторяется')),
                ('to_remind', models.BooleanField(verbose_name='напоминание')),
                ('remind_date', models.DateTimeField(blank=True, null=True, verbose_name='дата напоминания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiarySiteApp.category')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название тега')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiarySiteApp.category')),
                ('event', models.ManyToManyField(to='DiarySiteApp.Event')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
