# Generated by Django 3.2 on 2021-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiarySiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='название категории'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True, verbose_name='описание события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='remind_date',
            field=models.DateTimeField(null=True, verbose_name='дата напоминания'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='название тега'),
        ),
    ]
