# Generated by Django 3.2 on 2021-04-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiarySiteApp', '0002_alter_event_planned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='on_delete',
            field=models.BooleanField(default=False, verbose_name='удалено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='запланированная дата'),
        ),
    ]
