# Generated by Django 3.2 on 2021-04-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiarySiteApp', '0004_auto_20210418_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tags',
            new_name='tag',
        ),
    ]
